### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by Eeeeeediot** [thexperiments/hassio-addon-ikettle2mqtt#1]
![Screenshot_20210309-133310_Home Assistant](https://user-images.githubusercontent.com/31865648/110482570-b73a1a00-80e0-11eb-9787-652477e73d2c.jpg)

**Comment by thexperiments** [comment]
So the kettle IP is 192.168.0.9?
How did you find the IP address?
Can you ping that address from your machine? 
Can you ping it from Home assistant?
Are you using an iKettle 2.0?

**Comment by Eeeeeediot** [comment]
Yes
I pinged it with Fing and then unplugged it and ping didn't reach.
Using iKettle 3rd Gen - is it supported?

**Comment by thexperiments** [comment]
Sadly iKettle 3rd gen is not supported only iKettle 2.0 :(
I should update the description to make it more clear.

I could not find a nodejs library for the new kettle (with this available someone could easily make a version for the new kettle) and I don't own one.

**Comment by Eeeeeediot** [comment]
Gutted! Thanks anyways
